name: Deploy to NAS Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github-to-nas-deploy
          chmod 600 ~/.ssh/github-to-nas-deploy
          ssh-keyscan -p ${{ secrets.NAS_PORT }} -H ${{ secrets.NAS_HOST }} >> ~/.ssh/known_hosts

      - name: Create .env from secret
        run: |
          echo "${{ secrets.ENV_FILE_CONTENTS }}" > .

      - name: Test SSH Connection
        run: |
          ssh -i ~/.ssh/github-to-nas-deploy -p ${{ secrets.NAS_PORT }} ${{ secrets.NAS_USER }}@${{ secrets.NAS_HOST }} "echo 'SSH connection successful'"

      - name: Upload project to NAS
        run: |
          rsync -avz -e "ssh -i ~/.ssh/github-to-nas-deploy -p ${{ secrets.NAS_PORT }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ./ ${{ secrets.NAS_USER }}@${{ secrets.NAS_HOST }}:~/ezticket

      - name: Remote deploy
        run: |
          ssh -i ~/.ssh/github-to-nas-deploy -p ${{ secrets.NAS_PORT }} ${{ secrets.NAS_USER }}@${{ secrets.NAS_HOST }} << 'EOF'
            cd ~/ezticket
            docker-compose down
            docker-compose up -d --build
          EOF