name: Deploy to NAS Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.NAS_PORT }} -H ${{ secrets.NAS_HOST }} >> ~/.ssh/known_hosts
          echo "Host *" >> ~/.ssh/config

      - name: Create .env from secret
        run: |
          echo "${{ secrets.ENV_FILE_CONTENTS }}" > .env

      - name: Ensure target dir exists
        run: |
          ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.NAS_PORT }} ${{ secrets.NAS_USER }}@${{ secrets.NAS_HOST }} "mkdir -p ~/ezticket"

      - name: Upload project to NAS using SCP
        run: |
          scp -i ~/.ssh/id_ed25519 -P ${{ secrets.NAS_PORT }} -r ./ ${{ secrets.NAS_USER }}@${{ secrets.NAS_HOST }}:~/ezticket

      - name: Remote deploy
        run: |
          ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.NAS_PORT }} ${{ secrets.NAS_USER }}@${{ secrets.NAS_HOST }} << 'EOF'
            cd /var/services/homes/github-runner/ezticket
            docker-compose down
            docker-compose up -d --build
          EOF